/*
 * ThermoPhononsView.java
 *
 * Created on April 29, 2008, 6:14 PM
 */
package br.ufjf.quimica.gfqs.transitionstatetheory.view;

import br.ufjf.quimica.gfqsi.transitionstatetheroy.Configuration;
import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Ary Junior <a href="mailto:aryjunior@gmail.com">aryjunior@gmail.com</a>
 * @version $Id: TransitionStateTheoryView.java,v 1.1 2010-10-22 14:57:06 aryjr Exp $
 * 
 */
public class TransitionStateTheoryView extends JDialog {

    private Configuration reactant1;
    private Configuration reactant2;
    private Configuration transitionState;

    /** Creates new form ThermoPhononsView */
    public TransitionStateTheoryView(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtR1TotalEnergyFile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtR1PhononsFile = new javax.swing.JTextField();
        btnR1BrowsePhononsFile = new javax.swing.JButton();
        btnR1BrowseTotalEnergyFile = new javax.swing.JButton();
        chkR1Molecule = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkR1Linear = new javax.swing.JCheckBox();
        chkR1Polyatomic = new javax.swing.JCheckBox();
        lblR1SymmetryNumber = new javax.swing.JLabel();
        txtR1SymmetryNumber = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtR2TotalEnergyFile = new javax.swing.JTextField();
        btnR2BrowseTotalEnergyFile = new javax.swing.JButton();
        btnR2BrowsePhononsFile = new javax.swing.JButton();
        txtR2PhononsFile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chkR2Molecule = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chkR2Linear = new javax.swing.JCheckBox();
        chkR2Polyatomic = new javax.swing.JCheckBox();
        lblR2SymmetryNumber = new javax.swing.JLabel();
        txtR2SymmetryNumber = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtTSTotalEnergyFile = new javax.swing.JTextField();
        btnTSBrowseTotalEnergyFile = new javax.swing.JButton();
        btnTSBrowsePhononsFile = new javax.swing.JButton();
        txtTSPhononsFile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkTSMolecule = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        chkTSLinear = new javax.swing.JCheckBox();
        chkTSPolyatomic = new javax.swing.JCheckBox();
        lblTSSymmetryNumber = new javax.swing.JLabel();
        txtTSSymmetryNumber = new javax.swing.JTextField();
        cmbOutput = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbEnergyUnit = new javax.swing.JComboBox();
        btnCalculate = new javax.swing.JButton();
        lblPressure = new javax.swing.JLabel();
        txtPressure = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transition State Theory with phonons - version 1.0.0");

        jLabel4.setText("PWscf total energy file:");

        txtR1TotalEnergyFile.setEditable(false);

        jLabel5.setText("PWscf phonons file:");

        txtR1PhononsFile.setEditable(false);

        btnR1BrowsePhononsFile.setText("Browse");
        btnR1BrowsePhononsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1BrowsePhononsFileActionPerformed(evt);
            }
        });

        btnR1BrowseTotalEnergyFile.setText("Browse");
        btnR1BrowseTotalEnergyFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1BrowseTotalEnergyFileActionPerformed(evt);
            }
        });

        chkR1Molecule.setText("Molecule");
        chkR1Molecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkR1MoleculeActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Molecule options"));

        chkR1Linear.setText("Linear");
        chkR1Linear.setEnabled(false);

        chkR1Polyatomic.setSelected(true);
        chkR1Polyatomic.setText("Polyatomic");
        chkR1Polyatomic.setEnabled(false);

        lblR1SymmetryNumber.setText("Symmetry number:");
        lblR1SymmetryNumber.setEnabled(false);

        txtR1SymmetryNumber.setText("1");
        txtR1SymmetryNumber.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chkR1Polyatomic)
                        .addGap(18, 18, 18)
                        .addComponent(chkR1Linear))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblR1SymmetryNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtR1SymmetryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                .addGap(195, 195, 195))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkR1Linear)
                    .addComponent(chkR1Polyatomic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblR1SymmetryNumber)
                    .addComponent(txtR1SymmetryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(chkR1Molecule)
                            .addComponent(txtR1PhononsFile, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(txtR1TotalEnergyFile))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnR1BrowseTotalEnergyFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnR1BrowsePhononsFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtR1TotalEnergyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR1BrowseTotalEnergyFile))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtR1PhononsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR1BrowsePhononsFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkR1Molecule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reactant 1", jPanel1);

        jLabel9.setText("PWscf total energy file:");

        txtR2TotalEnergyFile.setEditable(false);

        btnR2BrowseTotalEnergyFile.setText("Browse");
        btnR2BrowseTotalEnergyFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2BrowseTotalEnergyFileActionPerformed(evt);
            }
        });

        btnR2BrowsePhononsFile.setText("Browse");
        btnR2BrowsePhononsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2BrowsePhononsFileActionPerformed(evt);
            }
        });

        txtR2PhononsFile.setEditable(false);

        jLabel10.setText("PWscf phonons file:");

        chkR2Molecule.setText("Molecule");
        chkR2Molecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkR2MoleculeActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Molecule options"));

        chkR2Linear.setText("Linear");
        chkR2Linear.setEnabled(false);

        chkR2Polyatomic.setSelected(true);
        chkR2Polyatomic.setText("Polyatomic");
        chkR2Polyatomic.setEnabled(false);

        lblR2SymmetryNumber.setText("Symmetry number:");
        lblR2SymmetryNumber.setEnabled(false);

        txtR2SymmetryNumber.setText("1");
        txtR2SymmetryNumber.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chkR2Polyatomic)
                        .addGap(18, 18, 18)
                        .addComponent(chkR2Linear))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblR2SymmetryNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtR2SymmetryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                .addGap(196, 196, 196))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkR2Linear)
                    .addComponent(chkR2Polyatomic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblR2SymmetryNumber)
                    .addComponent(txtR2SymmetryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(chkR2Molecule)
                            .addComponent(txtR2PhononsFile, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtR2TotalEnergyFile, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnR2BrowseTotalEnergyFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnR2BrowsePhononsFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtR2TotalEnergyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR2BrowseTotalEnergyFile))
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtR2PhononsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR2BrowsePhononsFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkR2Molecule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reactant 2", jPanel2);

        jLabel11.setText("PWscf total energy file:");

        txtTSTotalEnergyFile.setEditable(false);

        btnTSBrowseTotalEnergyFile.setText("Browse");
        btnTSBrowseTotalEnergyFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSBrowseTotalEnergyFileActionPerformed(evt);
            }
        });

        btnTSBrowsePhononsFile.setText("Browse");
        btnTSBrowsePhononsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSBrowsePhononsFileActionPerformed(evt);
            }
        });

        txtTSPhononsFile.setEditable(false);

        jLabel12.setText("PWscf phonons file:");

        chkTSMolecule.setText("Molecule");
        chkTSMolecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTSMoleculeActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Molecule options"));

        chkTSLinear.setText("Linear");
        chkTSLinear.setEnabled(false);

        chkTSPolyatomic.setSelected(true);
        chkTSPolyatomic.setText("Polyatomic");
        chkTSPolyatomic.setEnabled(false);

        lblTSSymmetryNumber.setText("Symmetry number:");
        lblTSSymmetryNumber.setEnabled(false);

        txtTSSymmetryNumber.setText("1");
        txtTSSymmetryNumber.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chkTSPolyatomic)
                        .addGap(18, 18, 18)
                        .addComponent(chkTSLinear))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTSSymmetryNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTSSymmetryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                .addGap(192, 192, 192))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTSLinear)
                    .addComponent(chkTSPolyatomic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTSSymmetryNumber)
                    .addComponent(txtTSSymmetryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(chkTSMolecule)
                            .addComponent(txtTSTotalEnergyFile, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(txtTSPhononsFile))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTSBrowseTotalEnergyFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTSBrowsePhononsFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTSTotalEnergyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTSBrowseTotalEnergyFile))
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTSPhononsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTSBrowsePhononsFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTSMolecule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transition State", jPanel5);

        cmbOutput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Complete", "Internal energies versus temperatures", "Entropies versus temperatures", "Enthalpies versus temperatures", "Helmholtz energies versus temperatures", "Gibbs energies versus temperatures" }));
        cmbOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOutputActionPerformed(evt);
            }
        });

        jLabel6.setText("Output:");

        txtResults.setColumns(20);
        txtResults.setRows(5);
        jScrollPane1.setViewportView(txtResults);

        jLabel7.setText("Temperature(s) in Kelvin:");

        txtTemperature.setText("298.150");

        jLabel8.setText("Energy unit:");

        cmbEnergyUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kJ/mol", "kcal/mol", "eV" }));
        cmbEnergyUnit.setEnabled(false);

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblPressure.setText("Pressure (atm):");

        txtPressure.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalculate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTemperature, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbEnergyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPressure)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbOutput, 0, 385, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbEnergyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPressure)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnR1BrowsePhononsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1BrowsePhononsFileActionPerformed
        browseFile(txtR1PhononsFile);
    }//GEN-LAST:event_btnR1BrowsePhononsFileActionPerformed

    private void btnR1BrowseTotalEnergyFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1BrowseTotalEnergyFileActionPerformed
        browseFile(txtR1TotalEnergyFile);
    }//GEN-LAST:event_btnR1BrowseTotalEnergyFileActionPerformed

    private void browseFile(JTextField txt) {
        //JFileChooser fc = new JFileChooser(new File(System.getProperty("user.dir")));
        JFileChooser fc = new JFileChooser(new File("/home/aryjr/mestrado-ufjf/g-alumina/modelos/Krokidis/superficies/001-HMDS-C/c"));
        fc.addChoosableFileFilter(new OutFileFilter());
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            txt.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }

    private void cmbOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOutputActionPerformed
        cmbEnergyUnit.setEnabled(cmbOutput.getSelectedIndex() != 0);
}//GEN-LAST:event_cmbOutputActionPerformed

    private void chkR1MoleculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkR1MoleculeActionPerformed
        chkR1Polyatomic.setEnabled(chkR1Molecule.isSelected());
        chkR1Linear.setEnabled(chkR1Molecule.isSelected());
        txtR1SymmetryNumber.setEnabled(chkR1Molecule.isSelected());
        lblR1SymmetryNumber.setEnabled(chkR1Molecule.isSelected());
}//GEN-LAST:event_chkR1MoleculeActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

}//GEN-LAST:event_btnCalculateActionPerformed

    private void btnR2BrowseTotalEnergyFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2BrowseTotalEnergyFileActionPerformed
        browseFile(txtR2TotalEnergyFile);
    }//GEN-LAST:event_btnR2BrowseTotalEnergyFileActionPerformed

    private void btnR2BrowsePhononsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2BrowsePhononsFileActionPerformed
        browseFile(txtR2PhononsFile);
    }//GEN-LAST:event_btnR2BrowsePhononsFileActionPerformed

    private void chkR2MoleculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkR2MoleculeActionPerformed
        chkR2Polyatomic.setEnabled(chkR2Molecule.isSelected());
        chkR2Linear.setEnabled(chkR2Molecule.isSelected());
        txtR2SymmetryNumber.setEnabled(chkR2Molecule.isSelected());
        lblR2SymmetryNumber.setEnabled(chkR2Molecule.isSelected());
    }//GEN-LAST:event_chkR2MoleculeActionPerformed

    private void btnTSBrowseTotalEnergyFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSBrowseTotalEnergyFileActionPerformed
        browseFile(txtTSTotalEnergyFile);
    }//GEN-LAST:event_btnTSBrowseTotalEnergyFileActionPerformed

    private void btnTSBrowsePhononsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSBrowsePhononsFileActionPerformed
        browseFile(txtTSPhononsFile);
    }//GEN-LAST:event_btnTSBrowsePhononsFileActionPerformed

    private void chkTSMoleculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTSMoleculeActionPerformed
        chkTSPolyatomic.setEnabled(chkTSMolecule.isSelected());
        chkTSLinear.setEnabled(chkTSMolecule.isSelected());
        txtTSSymmetryNumber.setEnabled(chkTSMolecule.isSelected());
        lblTSSymmetryNumber.setEnabled(chkTSMolecule.isSelected());
    }//GEN-LAST:event_chkTSMoleculeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                TransitionStateTheoryView dialog = new TransitionStateTheoryView(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {

                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnR1BrowsePhononsFile;
    private javax.swing.JButton btnR1BrowseTotalEnergyFile;
    private javax.swing.JButton btnR2BrowsePhononsFile;
    private javax.swing.JButton btnR2BrowseTotalEnergyFile;
    private javax.swing.JButton btnTSBrowsePhononsFile;
    private javax.swing.JButton btnTSBrowseTotalEnergyFile;
    private javax.swing.JCheckBox chkR1Linear;
    private javax.swing.JCheckBox chkR1Molecule;
    private javax.swing.JCheckBox chkR1Polyatomic;
    private javax.swing.JCheckBox chkR2Linear;
    private javax.swing.JCheckBox chkR2Molecule;
    private javax.swing.JCheckBox chkR2Polyatomic;
    private javax.swing.JCheckBox chkTSLinear;
    private javax.swing.JCheckBox chkTSMolecule;
    private javax.swing.JCheckBox chkTSPolyatomic;
    private javax.swing.JComboBox cmbEnergyUnit;
    private javax.swing.JComboBox cmbOutput;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblR1SymmetryNumber;
    private javax.swing.JLabel lblR2SymmetryNumber;
    private javax.swing.JLabel lblTSSymmetryNumber;
    private javax.swing.JTextField txtPressure;
    private javax.swing.JTextField txtR1PhononsFile;
    private javax.swing.JTextField txtR1SymmetryNumber;
    private javax.swing.JTextField txtR1TotalEnergyFile;
    private javax.swing.JTextField txtR2PhononsFile;
    private javax.swing.JTextField txtR2SymmetryNumber;
    private javax.swing.JTextField txtR2TotalEnergyFile;
    private javax.swing.JTextArea txtResults;
    private javax.swing.JTextField txtTSPhononsFile;
    private javax.swing.JTextField txtTSSymmetryNumber;
    private javax.swing.JTextField txtTSTotalEnergyFile;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}

class OutFileFilter extends FileFilter {

    private String extension = ".out";

    public boolean accept(File file) {
        String filename = file.getName();
        return filename.indexOf(extension) > 0 || file.isDirectory();
    }

    public String getDescription() {
        return "*.out*";
    }
}
